# Generated by Django 4.2.1 on 2023-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=255)),
                ('weatherdate', models.DateField()),
                ('low_temperature', models.IntegerField()),
                ('high_temperature', models.IntegerField()),
                ('precipitation', models.IntegerField()),
            ],
            options={
                'ordering': ('weatherdate',),
            },
        ),
    ]
