# Generated by Django 4.2.1 on 2023-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathersummary",
            name="avg_max_temp",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weathersummary",
            name="avg_min_temp",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weathersummary",
            name="avg_precipitation",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
