# Generated by Django 4.2.1 on 2023-05-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_weathersummary_avg_max_temp_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Weather_data",
            new_name="SourceData",
        ),
    ]
